name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  mobile_scanner: ^3.5.0 # QR kod okuma
  dio: ^5.4.0 # Dosya indirme
  open_filex: ^4.3.4 # İndirilen APK’yı açma
  path_provider: ^2.1.2 # Dosya indirme yolu
  # UI ve İkonlar
  cupertino_icons: ^1.0.8

  # Bluetooth ve Navigasyon
  flutter_blue_plus: ^2.0.0
  permission_handler: ^12.0.1
  video_player: ^2.10.0
  speech_to_text: ^7.3.0

  # Modern UI Bileşenleri
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # <<< YENİ EKLENEN ÖNBELLEK PAKETLERİ >>>
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  # <<< EKLENTİLER SONU >>>

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
