name: flutter_application_1
description: "A new Flutter project."
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # UI ve İkonlar
  cupertino_icons: ^1.0.8
  
  # Bluetooth ve Navigasyon
  flutter_blue_plus: ^2.0.0
  permission_handler: ^12.0.1
  video_player: ^2.10.0
  speech_to_text: ^7.3.0
  flutter_compass: ^0.8.0
  
  # Modern UI Bileşenleri
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # ÖNBELLEK PAKETLERİ VE HARİTA
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # YEREL VARLIK YOLLARI (Tüm POI klasörlerini kapsayacak şekilde genişletildi)
  assets:
    # Ana dizin ve Haritalar
    - assets/
    
    # Tüm POI Klasörleri (Ekran görüntünüzdeki yapıya göre)
    - assets/AktiviteOdasi/
    - assets/AsansorKat1/
    - assets/AsansorKat2/
    - assets/AsansorZemin/
    - assets/BeklemeSalonu/
    - assets/BilgisayarLabKat1/
    - assets/DanismaMasasi/
    - assets/GirisCikis/
    - assets/IdariOfisKat1/
    - assets/LYECGirisKat2/
    - assets/MerdivenKat1/
    - assets/MerdivenZemin/
    - assets/Mutfak/
    - assets/MutfakKat2/
    - assets/MuzikOdasi/
    - assets/OgretmenOdasi/
    - assets/ResimAtolyesi/
    - assets/Revir/
    - assets/SesliKutuphane/
    - assets/Teras1/
    - assets/Teras2/
    - assets/toluhoca/
    - assets/WCKat1/
    - assets/WCZemin/